project:
  name: investment-tool
  version: 1.3.1
  file:
    upload:
      root-dir: ${user.home}/dev/investment-tool/uploads
      max-size: 10MB
      allowed-types:
        - image/jpeg
        - image/jpg
        - image/png

server:
  port: 8888

spring:
  application:
    name: investment-tool
  datasource:
    url: jdbc:mysql://localhost:3306/investment_tool?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启 SQL 日志
  global-config:
    db-config:
      id-type: auto  # 主键自增
